# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2026-present Datadog, Inc.

# Generated by scripts/homebrew.rb in datadog-labs/bits-cli from
# .github/homebrew/bits.rb.erb; change the formula there.
class Bits < Formula
  desc "Datadog Assistant in your terminal"
  homepage "https://github.com/datadog-labs/bits-cli"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/datadog-labs/bits-cli/releases/download/v0.0.7/bits_0.0.7_darwin_arm64.tar.gz"
      sha256 "3753d2103c0974ef7040bdd5864cc3a844067c1e323606fe3e7d6cf9f57860db"
    end
    on_intel do
      url "https://github.com/datadog-labs/bits-cli/releases/download/v0.0.7/bits_0.0.7_darwin_amd64.tar.gz"
      sha256 "1d34400b30d6b49fca331d9fbb33a2f07b16f5cae09dc6f329ef6e1d20a8afcf"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/datadog-labs/bits-cli/releases/download/v0.0.7/bits_0.0.7_linux_arm64.tar.gz"
      sha256 "8ea62b433f5dbde1f962c40b5aec327bdc84587c24abe59e523310ed1898a6a9"
    end
    on_intel do
      url "https://github.com/datadog-labs/bits-cli/releases/download/v0.0.7/bits_0.0.7_linux_amd64.tar.gz"
      sha256 "3f49d5391548348f20b33d6d9e9019da1400c98946b38d59564293f76b9546cb"
    end
  end

  def install
    bin.install "bits"
  end

  test do
    assert_equal "bits version v#{version}", shell_output("#{bin}/bits --version").strip
  end
end
