# Trust policy for pup release workflow to push Homebrew formulas
issuer: https://token.actions.githubusercontent.com

# Allow releases from semantic version tags (v1.2.3, v0.1.0, etc.)
subject_pattern: repo:DataDog/pup:ref:refs/tags/v[0-9]+\.[0-9]+\.[0-9]+

# Defense-in-depth: additional claim validation
claim_pattern:
  event_name: push
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/pup/\.github/workflows/release\.yml@refs/tags/v[0-9]+\.[0-9]+\.[0-9]+

# Grant write access to push formula updates
permissions:
  contents: write
