# Trust policy for pup release workflow to push Homebrew formulas
issuer: https://token.actions.githubusercontent.com

# Only from datadog-labs/pup repository
subject_pattern: repo:datadog-labs/pup:.*

# Defense-in-depth: additional claim validation
claim_pattern:
  event_name: push
  # Allow releases from semantic version tags (v1.2.3, v0.1.0, etc.)
  ref: refs/tags/v[0-9]+\.[0-9]+\.[0-9]+
  # Only from the release workflow
  job_workflow_ref: datadog-labs/pup/\.github/workflows/release\.yml@.*

# Grant write access to push formula updates
permissions:
  contents: write
